# Generated by Django 6.0 on 2026-01-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notify_email',
            field=models.CharField(blank=True, help_text='Emails to notify (comma-separated for multiple friends)', max_length=500, null=True),
        ),
    ]
