# Generated by Django 5.1.2 on 2026-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_profile_notify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('energetic', '⚡ Energetic'), ('calm', '🧘 Calm'), ('romantic', '💖 Romantic'), ('productive', '🚀 Productive'), ('melancholy', '☁️ Melancholy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
